name: sacco
description: Pure Dart library allowing you to easily create an HD Wallet and create, sign and send Cosmos-SDK transactions.
version: 0.1.5
homepage: https://github.com/commercionetwork/sacco.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.2.3
  hex: ^0.1.2
  http: ^0.12.2
  equatable: ^1.2.5
  json_annotation: ^3.0.1


  # Crypto utils
  asn1lib: ^0.6.5
  bip32: ^1.0.7
  bip39: ^1.0.3
  bitcoin_flutter: ^2.0.1
  pointycastle: ^1.0.2
  bip_bech32: ^0.1.3

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.9+1
  json_serializable: ^3.2.0
  test: ^1.6.8
