name: sacco
description: Pure Dart library allowing you to easily create an HD Wallet and create, sign and send Cosmos-SDK transactions.
version: 0.1.5
homepage: https://github.com/commercionetwork/sacco.dart

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  bip32: ^1.0.8
  bip_bech32: ^0.1.3
  equatable: ">=2.0.0 <3.0.0"
  http: ">=0.13.0 <0.14.0"
  json_annotation: ">=4.0.0 <5.0.0"

dev_dependencies:
  build_runner: ">=1.11.0 <1.12.0"
  json_serializable: ">=4.0.0 <5.0.0"
  test: ">=1.16.0 <2.0.0"

dependency_overrides:
  # pointycastle v2.0.1 uses BigInt encoding/decoding in twos compliment, thus breaking bip32 v1.0.8
  pointycastle: 2.0.0
