name: sacco
description: Pure Dart library allowing you to easily create an HD Wallet and create, sign and send Cosmos-SDK transactions.
version: 0.1.5
homepage: https://github.com/commercionetwork/sacco.dart

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.2.4
  http: ^0.12.2
  equatable: ^2.0.0
  json_annotation: ^4.0.0


  # Crypto utils
  asn1lib: ^0.9.0-nullsafety.0
  bip32: ^1.0.8
  bip39: ^1.0.4
  pointycastle: ^2.0.1
  bip_bech32: ^0.1.3

dev_dependencies:
  build_runner: ^1.11.1
  build_test: ^1.3.6
  json_serializable: ^4.0.2
  test: ^1.15.7
